import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import RecentPost from "./components/recentPost";

import "./globals.css";
import Hero from "./components/Hero";
import FeaturedWorks from "./components/FeaturedWorks";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-black antialiased`}
      ><Navbar />
      <Hero />
      <RecentPost />
      <FeaturedWorks/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
